#!/usr/bin/env node
// ============================================================
// Permutation test harness for ASCII <-> Unicode conversion.
//
// Generates every consonant x vowel-sign syllable, halant forms,
// anusvara/visarga forms, and all two-consonant conjuncts, then
// verifies Unicode -> ASCII -> Unicode round-trips for each font.
//
// Usage:   node test/permutations.js [--full]
// Output:  test/ISSUES.md (regenerated on every run)
// Exit:    0 if no failures, 1 otherwise
//
// Run this after every conversion fix - it is the guard against
// fixing one case and silently breaking another.
// ============================================================

const fs = require('fs');
const path = require('path');

// ---- load app.js in a headless stub ----
const stubEl = new Proxy({}, {
    get(t, p) {
        if (p === 'addEventListener') return () => {};
        if (p === 'style') return { setProperty() {} };
        if (p === 'classList') return { add() {}, remove() {}, toggle() {} };
        if (p === 'value') return '';
        return () => {};
    }
});
global.document = {
    addEventListener() {},
    getElementById() { return stubEl; },
    querySelector() { return null; },
    querySelectorAll() { return []; }
};
global.window = global;
global.navigator = { userAgent: 'test-harness' };

// eslint-disable-next-line no-eval
eval(fs.readFileSync(path.join(__dirname, '..', 'js', 'app.js'), 'utf8'));

// ---- case generation ----
const CONSONANTS = [...'ಕಖಗಘಙಚಛಜಝಞಟಠಡಢಣತಥದಧನಪಫಬಭಮಯರಲವಶಷಸಹಳ'];
const MATRAS = [...'ಾಿೀುೂೃೆೇೈೊೋೌ'];
const VOWELS = [...'ಅಆಇಈಉಊಋಎಏಐಒಓಔ'];
const FULL = process.argv.includes('--full');

function buildCases() {
    const cases = [];
    const add = (label, text) => cases.push({ label, text });

    VOWELS.forEach(v => add('vowel', v));
    CONSONANTS.forEach(c => {
        add('syllable', c);                       // bare consonant
        add('halant-final', c + '್');             // final halant
        MATRAS.forEach(m => add('syllable', c + m));
        add('anusvara', c + 'ಂ');
        add('visarga', c + 'ಃ');
    });

    // two-consonant conjuncts: C1 + virama + C2 (all pairs)
    CONSONANTS.forEach(c1 => CONSONANTS.forEach(c2 => {
        add('conjunct', c1 + '್' + c2);
    }));

    // conjunct + matra (sampled matras unless --full)
    const conjMatras = FULL ? MATRAS : [...'ಾಿುೆೋ'];
    CONSONANTS.forEach(c1 => conjMatras.forEach(m => {
        add('conjunct+matra', c1 + '್ಕ' + m);     // C1 + ka + matra
        add('conjunct+matra', 'ಕ್' + c1 + m);     // ka + C2 + matra
    }));

    // specials
    ['ಕ್ಷ', 'ಜ್ಞ', 'ಕ್ಷಿ', 'ಜ್ಞಾ', 'ಸ್ತ್ರೀ', 'ಷ್ಟ್ಯ', 'ರ್ಕ', 'ರ್ಮ', 'ಕರ್ನಾಟಕ',
     'ಕನ್ನಡ', 'ನನ್', 'ಅಕ್ಕ', 'ಅಪ್ಪ', 'ಭಾಷ್ಯ', 'ವೈಶಿಷ್ಟ್ಯ', 'ಸಂಸ್ಕೃತಿ',
     'ಅಂಗಡಿ', 'ಇಂದು', 'ದುಃಖ', 'ಋಷಿ', 'ಔಷಧ'].forEach(w => add('word', w));

    // mixed English/number retention
    [['mixed', 'ಕನ್ನಡ hello 123'], ['mixed', 'ಬೆಲೆ ರೂ. 45.50'],
     ['mixed', 'test ಪರೀಕ್ಷೆ 2024']].forEach(([l, t]) => add(l, t));

    return cases;
}

// ---- run ----
const FONTS = ['nudi', 'shree', 'prakashak', 'akruti'];
const cases = buildCases();
const results = {};
let totalFail = 0;

for (const font of FONTS) {
    const failures = [];
    for (const { label, text } of cases) {
        let ascii, back, err = null;
        try {
            ascii = convert(text, 'keep', 'u2a', true, font);
            back = convert(ascii, 'keep', 'a2u', true, font);
        } catch (e) { err = e.message; }
        if (err || back !== text) {
            // Attribute the failure to a direction:
            //  - Kannada characters left in the ASCII output (or an exception
            //    during u2a) -> the Unicode->ASCII side is incomplete
            //  - clean ASCII that does not round-trip -> ASCII->Unicode side
            const dir = (err || /[ಀ-೿]/.test(ascii || '')) ? 'u2a' : 'a2u';
            failures.push({ label, text, ascii, back, err, dir });
        }
    }
    results[font] = failures;
    totalFail += failures.length;
}

// ---- write stats.json (rendered by status.html) ----
const stats = {
    generated: new Date().toISOString().slice(0, 10),
    casesPerFont: cases.length,
    fonts: {}
};
for (const font of FONTS) {
    const fails = results[font];
    const byLabel = {};
    let u2aFail = 0, a2uFail = 0;
    fails.forEach(f => {
        byLabel[f.label] = (byLabel[f.label] || 0) + 1;
        if (f.dir === 'u2a') u2aFail++; else a2uFail++;
    });
    stats.fonts[font] = {
        pass: cases.length - fails.length,
        fail: fails.length,
        u2aFail: u2aFail,
        a2uFail: a2uFail,
        categories: byLabel
    };
}
fs.writeFileSync(path.join(__dirname, 'stats.json'), JSON.stringify(stats, null, 2));

// ---- write ISSUES.md ----
const lines = [];
lines.push('# Conversion issue log');
lines.push('');
lines.push('Auto-generated by `node test/permutations.js` - do not edit by hand.');
lines.push('Re-run after every conversion fix to confirm nothing regressed.');
lines.push('');
lines.push(`Last run: ${new Date().toISOString().slice(0, 10)} | Cases per font: ${cases.length}`);
lines.push('');
lines.push('| Font | Pass | Fail |');
lines.push('|------|------|------|');
for (const font of FONTS) {
    lines.push(`| ${font} | ${cases.length - results[font].length} | ${results[font].length} |`);
}
lines.push('');

for (const font of FONTS) {
    const fails = results[font];
    if (!fails.length) { lines.push(`## ${font}: all ${cases.length} cases pass\n`); continue; }
    lines.push(`## ${font}: ${fails.length} failures`);
    lines.push('');
    // group by category
    const byLabel = {};
    fails.forEach(f => { (byLabel[f.label] = byLabel[f.label] || []).push(f); });
    for (const [label, group] of Object.entries(byLabel)) {
        lines.push(`### ${label} (${group.length})`);
        lines.push('');
        lines.push('| Input (Unicode) | u2a output | a2u round-trip | Error |');
        lines.push('|---|---|---|---|');
        const shown = group.slice(0, 15);
        for (const f of shown) {
            const esc = s => (s === undefined || s === null) ? '' : String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
            lines.push(`| ${esc(f.text)} | \`${esc(f.ascii)}\` | ${esc(f.back)} | ${esc(f.err || '')} |`);
        }
        if (group.length > shown.length) lines.push(`| ... ${group.length - shown.length} more | | | |`);
        lines.push('');
    }
}

fs.writeFileSync(path.join(__dirname, 'ISSUES.md'), lines.join('\n'));

// ---- console summary ----
console.log(`Cases per font: ${cases.length}`);
for (const font of FONTS) {
    const f = results[font].length;
    console.log(`${font.padEnd(10)} ${f === 0 ? 'PASS' : 'FAIL'}  ${cases.length - f}/${cases.length} pass`);
}
console.log(totalFail ? `\n${totalFail} total failures -> test/ISSUES.md` : '\nAll fonts fully pass.');
process.exit(totalFail ? 1 : 0);
