#!/usr/bin/env python3
"""
Generate JS "X -> Nudi ASCII" pivot maps from the resolved macro rule tables.

Reads tools/macro-extracts/*.resolved.json (falls back to the unresolved
.json if no .resolved.json exists) and emits one JS const per font:

    const PRAKASH2_X2NUDI = {34:"C",35:"Ä", ...};  // charCode -> Nudi ASCII fragment

Output is a single JS file (tools/pivot-maps.generated.js) meant to be
reviewed and then pasted/spliced into js/app.js (and server.js) near the
other font maps. Also prints a coverage summary per font to stdout.

Usage: python3 tools/generate-pivot-maps.py
"""
import json
import os

BASE = os.path.join(os.path.dirname(__file__), 'macro-extracts')

# (source json file, sub name within it, JS const name, display name)
TARGETS = [
    ('WinKey-Nudi_Conversions.json', 'PrakashakPrajaToNudiMono', 'PRAKASH2_X2NUDI', 'Prakashak (Praja)'),
    ('WinKey-Nudi_Conversions.json', 'AkrutiMono2NudiMono', 'AKRUTI2_X2NUDI', 'Akruti Mono'),
    ('SriLipi-Nudi_Conversion.json', 'SriLipiKAN850ToNudiMono', 'SHREE2_X2NUDI', 'SriLipi KAN-850'),
    ('Surabhi-Nudi_Conversion.json', 'SurabhiKNDSeriesToNudiMono', 'SURABHI_X2NUDI', 'Surabhi KND-series'),
]


def js_string(s):
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif o == 10:
            out.append('\\n')
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append('\\u%04x' % o)
    out.append('"')
    return ''.join(out)


def load(fname):
    resolved = os.path.join(BASE, fname[:-5] + '.resolved.json')
    if os.path.exists(resolved):
        return json.load(open(resolved, encoding='utf-8'))
    return json.load(open(os.path.join(BASE, fname), encoding='utf-8'))


def main():
    lines = []
    lines.append('// AUTO-GENERATED by tools/generate-pivot-maps.py - do not hand-edit.')
    lines.append('// Source: tools/macro-extracts/*.resolved.json (see tools/MACRO-REVIEW.md)')
    lines.append('// charCode (source encoding byte) -> Nudi ASCII fragment')
    lines.append('')
    summary = []
    for fname, sub_name, const_name, label in TARGETS:
        data = load(fname)
        sub = data[sub_name]
        rules = sub['rules']
        entries = []
        unresolved_codes = []
        seen_codes = set()
        for r in rules:
            codes = r['cases']
            if r.get('output') is not None:
                for c in codes:
                    if c in seen_codes:
                        continue
                    seen_codes.add(c)
                    entries.append((c, r['output']))
            else:
                unresolved_codes.extend(codes)
        entries.sort(key=lambda e: e[0])
        body = ','.join('%d:%s' % (c, js_string(v)) for c, v in entries)
        lines.append('// %s - %d/%d byte codes mapped (%d unresolved: %s)' % (
            label, len(entries), len(entries) + len(unresolved_codes), len(unresolved_codes),
            ','.join(str(c) for c in sorted(unresolved_codes)) or 'none'))
        lines.append('const %s = {%s};' % (const_name, body))
        lines.append('')
        summary.append((label, const_name, len(entries), len(unresolved_codes)))

    out_path = os.path.join(os.path.dirname(__file__), 'pivot-maps.generated.js')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print('Wrote', out_path)
    for label, const_name, mapped, unresolved in summary:
        print('  %-22s %-18s mapped=%-4d unresolved=%d' % (label, const_name, mapped, unresolved))


if __name__ == '__main__':
    main()
